### ISSUE TITLE
older versions of ensembldb

### ISSUE THREAD

**Issue by ahdee** [MattBashton/grolar#2]
Depending on the version of ensembldb, 
GeneIdFilter function is actually GeneidFilter from the vigenette 
"GeneidFilter creates a GeneIdFilter. Use GeneIdFilter instead" 

thanks.

**Comment by MattBashton** [comment]
I'm not going to support older versions of ensembldb, GeneIdFilter is the current filter name and is the filter I'm using, please update your version of bioconductor and ensembldb if your having issues.
